name: ourcommunity
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.1
  google_fonts: ^6.3.2
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  string_similarity: ^2.1.1
  supabase_flutter: ^2.10.1

flutter:
  uses-material-design: true
  assets:
    - asset/images/
